export const GET_CURRENCY_BITCOIN = 'GET_CURRENCY_BITCOIN';
export const GET_CURRENCY_BITCOIN_CASH = 'GET_CURRENCY_BITCOIN_CASH';
export const GET_CURRENCY_RIPPLE = 'GET_CURRENCY_RIPPLE';
export const GET_CURRENCY_ETHEREUM = 'GET_CURRENCY_ETHEREUM';
export const GET_CURRENCY_LITECOIN = 'GET_CURRENCY_LITECOIN';

export const GET_CURRENCY_BITCOIN_BITSO = 'GET_CURRENCY_BITCOIN_BITSO';
export const GET_CURRENCY_BITCOIN_CASH_BITSO = 'GET_CURRENCY_BITCOIN_CASH_BITSO';
export const GET_CURRENCY_RIPPLE_BITSO = 'GET_CURRENCY_RIPPLE_BITSO';
export const GET_CURRENCY_ETHEREUM_BITSO = 'GET_CURRENCY_ETHEREUM_BITSO';
export const GET_CURRENCY_LITECOIN_BITSO = 'GET_CURRENCY_LITECOIN_BITSO';

export const SETTING_COOKIE = 'SETTING_COOKIE';
export const GETTING_COOKIE = 'GETTING_COOKIE';
export const SETTING_CONFIG_COOKIE = 'SETTING_CONFIG_COOKIE';
export const GETTING_CONFIG_COOKIE = 'GETTING_CONFIG_COOKIE';
export const SET_OLD_CURRENCIES = 'SET_OLD_CURRENCIES';
export const SET_UPDATE_FALSE = 'SET_UPDATE_FALSE';
